name: Insert Comment on Push

on:
  push:
    branches:
      - master  # または任意のブランチ名

jobs:
  insert-comment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install GitPython

      - name: Get list of changed files
        id: changed
        run: |
          git fetch origin master
          git diff --name-only HEAD^ HEAD > changed_files.txt # 変更のあった部分をファイルで保存
          echo "Changed files:"
          cat changed_files.txt

      - name: Run comment inserter on changed files
        run: |
          python scripts/insert_comment.py changed_files.txt

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git diff --cached --quiet || (git commit -m "Auto-insert author/date/history comments" && git push)
